# MySQL
spring:
  datasource:
    url: jdbc:mysql://k8a104.p.ssafy.io:3306/daldong?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  # database pool
  datasource.hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    pool-name: HikariCP

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope:
              - email
              - profile
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
  redis:
    lettuce:
      pool:
        max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
        max-idle: 5 # pool의 'idle' 커넥션 최대수
        min-idle: 2
    host: 172.17.0.6
    port: 6379

jwt:
  secret: 
