# MySQL ?? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daldong?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

    # ???? spring.io?? doc?? ??? ??????.
    # jpa??