# Use an official Python runtime as a parent image
FROM python:3.9.13

# Copy the application code into the container
COPY . /app

# Set the working directory for subsequent instructions
RUN cd /app

# Copy the requirements file into the container
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose port 8000 for the application
EXPOSE 8000

# Start the application
CMD ["uvicorn", "app.main:app", "--reload"]
